export const INITIAL_STATE = {
  isLoggedIn: false,
  currentUser: false,
  errorMessage: "",
  loading: {
    register: false,
    login: false,
    logout: false,
    sendVerifyOtp: false,
    verifyUser: false,
    sendResetOtp: false,
    verifyResetOtp: false,
    resetPassword: false,
  },
  success: {
    register: false,
    login: false,
    logout: false,
    sendVerifyOtp: false,
    verifyUser: false,
    sendResetOtp: false,
    verifyResetOtp: false,
    resetPassword: false,
  },
  error: {
    register: false,
    login: false,
    logout: false,
    sendVerifyOtp: false,
    verifyUser: false,
    sendResetOtp: false,
    verifyResetOtp: false,
    resetPassword: false,
  },
};
